# Generated by Django 4.2.7 on 2023-11-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID университета')),
                ('fullName', models.CharField(max_length=20, unique=True, verbose_name='Полное название')),
                ('shortName', models.CharField(max_length=6, verbose_name='Сокращенное название')),
                ('year', models.DateField(verbose_name='Год основания')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID студента')),
                ('fullName', models.CharField(verbose_name='ФИО')),
                ('birthDate', models.DateField(verbose_name='Дата рождения')),
                ('admissionYear', models.DateField(verbose_name='Дата поступления')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app.universities', verbose_name='Университет')),
            ],
        ),
    ]
