# Generated by Django 4.2.7 on 2023-11-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_universities_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='fullName',
            field=models.CharField(max_length=100, unique=True, verbose_name='Полное название'),
        ),
    ]
